# Generated by Django 3.0.7 on 2020-07-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='Used',
            new_name='used',
        ),
    ]
