# Generated by Django 3.0.7 on 2020-07-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ads_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='region',
            field=models.CharField(choices=[('Upper West', 'Upper West'), ('Upper East', 'Upper East'), ('North East', 'North East'), ('Northen', 'Northen'), ('Savannah', 'Savannah'), ('Bono East', 'Bono East'), ('Brong Ahafo', 'Brong Ahafo'), ('Oti', 'Oti'), ('Ahafo', 'Ahafo'), ('Ashanti', 'Ashanti'), ('Volta', 'Volta'), ('Greater Accra', 'Greater Accra'), ('Western North', 'Western North'), ('Western', 'Western'), ('Eastern', 'Eastern'), ('Central', 'Central')], max_length=200, null=True),
        ),
    ]
