# Generated by Django 3.0.7 on 2020-07-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20200714_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='phone_number',
        ),
    ]
