# Generated by Django 3.0.7 on 2020-07-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
